[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.136.3",
    "numpy>=2.4.6",
    "python-dotenv>=1.2.2",
    "redis>=8.0.0",
    "redis-cli>=1.0.1",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "supabase>=2.31.0",
]
